# mise settings set experimental true
# mise install

[tools]
cmake = "4.3.0"
"conda:make" = "4.4.1"
ninja = "1.13.2"
"pipx:clang-format" = "22.1.1"
"pipx:clang-tidy" = "22.1.0"
"pipx:cppcheck" = "1.5.1"
