# Example usage:
# Build:
#   docker buildx build --platform linux/arm/v8 -f scripts/tests/docker/Dockerfile.armv8 -t test:armv8 . --load
# Run:
#   docker run --rm -it --platform linux/arm/v8 test:armv8

# Base
FROM arm64v8/ubuntu:latest AS base
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    cmake \
    ninja-build \
    lld \
    git \
    ca-certificates \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi

# Build
FROM base AS build
COPY . /test
WORKDIR /test
RUN cmake --workflow --preset default

ENTRYPOINT []
CMD ["ctest", "--preset", "default"]
