# Example usage:
# Build:
#   docker buildx build --platform linux/arm64 -f scripts/tests/docker/Dockerfile.arm64 -t test:arm64 . --load
# Run:
#   docker run --rm -it --platform linux/arm64 test:arm64

# Base
FROM ubuntu:latest AS base
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    cmake \
    ninja-build \
    lld \
    git \
    ca-certificates \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi

# Build
FROM base AS build
COPY . /test
WORKDIR /test
RUN cmake --workflow --preset default

ENTRYPOINT []
CMD ["ctest", "--preset", "default"]
